### ISSUE TITLE
How IdentityPython/idpy-oidc is different from OpenIDC/pyoidc and JWTConnect-Python-OidcRP?

### ISSUE THREAD

**Issue by infohash** [IdentityPython/idpy-oidc#53]
I want to contribute to a standardized and certified library that implements OIDC. [OpenID Foundation lists 3 certified Python libraries](https://openid.net/developers/certified/) for OIDC:

1. IdentityPython/idpy-oidc - 2nd layer in the JwtConnect stack (cryptojwt, idpyoidc)
2. [IdentityPython/JWTConnect-Python-OidcRP](https://github.com/IdentityPython/JWTConnect-Python-OidcRP) - 3rd layer in the JWTConnect stack (cryptojwt, oidcmsg, oidcrp)
3. [OpenIDC/pyoidc](https://github.com/OpenIDC/pyoidc) - Implements both client and the provider.

All of them are maintained by @rohe . This got me confused about which is the latest officially maintained lib for Python especially the difference between 1 and 2 as they are being maintained under the same org.

Edit: The docs in `/idpy-oidc/docs/move.rst` says that **idpy-oidc** is a successor of **JWTConnect-Python-OidcRP** and packages former libraries into this one:
1. OidcMsg -> idpy-oidc/message
2. OidcRP -> idpy-oidc/client
3. oidc-op -> idpy-oidc/server

This should be mentioned in the docs of former libs that they will not be supported in future. I almost believed that **JWTConnect-Python-OidcRP** is the successor because it says 3rd layer in its docs while idpy-oidc as the 2nd layer.

**Comment by sauerburger** [comment]
I'm in the same state of confusion. Since your post, the project
- https://github.com/IdentityPython/JWTConnect-Python-OidcRP was marked as `archive`, while
- https://github.com/CZ-NIC/pyoidc seems to be actively maintained.

The fact that the link to the [official docs](https://idpyoidc.readthedocs.io/) is broken in this project, adds to the confusion.

**Comment by c00kiemon5ter** [comment]
Hello everyone,

I can understand how things might be confusion because of the number of repos that are out there. Let's take it in steps.

Roland has created and maintained multiple libraries over the years, and we are thankful for that. IdentityPython was created as a space to gather and host libraries related to identity. Initially, under IdentityPython we had [pyop](https://github.com/IdentityPython/pyop). Later on, Roland brought the JWTConnect-Python libs. From those, [oidcendpoint](https://github.com/IdentityPython/oidcendpoint) became the primary library connecting and using everything else. After discussions, and to simplify the dependencies and usage, the layout changed and [oidc-op](https://github.com/IdentityPython/oidc-op) was released. When the work on JAR and PAR started, we discussed again that having "OP" in the name was not correct, as now the roles of entities changed and an entity could behave both as an OP and as a client/RP at the same time. Thus, [idpy-oidc](https://github.com/IdentityPython/idpy-oidc) came to be.

Apart from `pyop`, the other libs are an evolution of one over the other.
The current work is on `idpy-oidc`, and everything should be regarded as deprecated or be archived.

The reason that not all libs are archived is because they are still used. Once we know that their usage has stopped and that people have switched to the new lib, the repos will be archived.

---

The above covers what happens within IdentityPython. `pyoidc` is not hosted or controlled by us. It used to be under the OpenIDC but had been unmaintained for some time. AFAIU, it was transferred under CZ-NIC to be properly worked on and maintained.

`pyoidc` and `idpy-oidc` have taken different paths and support different specs and RFCs.
I have not followed the latest work on `pyoidc`, but I think that `idpy-oidc` supports a lot more use cases; at the cost of being more complex.

---

I hope this clears up a bit the space with those libs. Please, ask away if you need for info.
I agree that this should be properly documented in the repos so that it is more visible and less confusing.
